# Site settings
title: Jesse Zhou, UCSD 2017
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am an aspiring programmer pursuing a bachelor's degree in Computer Science.
  Currently attempting to discover the ways of the universe.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  jezhou

# Build settings
markdown: kramdown
