# Site settings
title: Jesse Zhou, UCSD 2017
email: jez017@ucsd.edu
description: > # this means to ignore newlines until "baseurl:"
  I am an aspiring programmer pursuing a bachelor's degree in Computer Science.
  Currently attempting to discover the ways of the universe.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

#Usernames
github_username:  jezhou
instagram_username: jezhou
twitter_username: yozhou

#Outputting
permalink: pretty

# Build settings
markdown: kramdown

# Collections
collections:
  projects: 
    output: true
